SUBDIR = array compute fd fifo fork forkwait llist main memsnap \
	 mmap multithread register pipe posix posixshm \
	 print sharemap selfie signal sleep slsfs socketpair sysvshm \
	 tcplisten udplisten unixlisten vmobject unlink wal

.include <bsd.subdir.mk>

.include <bsd.prog.mk>
