SUBDIR = array compute fd fifo fork llist main memory mmap \
	 multithread register pipes posixshm print sharemap \
	signal sleep slsfs socketpair sysvshm tcplisten udplisten \
	unixlisten unlink

.include <bsd.subdir.mk>

.include <bsd.prog.mk>
