SUBDIR = array compute fd fifo fork forkwait journal kqueue llist main memsnap \
	 metropolis mmap multithread register pipe pgroup posixshm \
	 print pymetro pymetro-partition sharemap selfie signal sleep \
	 slsfs socketpair sysvshm tcplisten udplisten unixlisten unlink wal

BINDIR=/usr/aurora/tests
.MAKE.EXPORTED=BINDIR

.include <bsd.subdir.mk>
