#!/bin/sh

export SRCROOT=..
MDDISK=""
export KTRLOG="ktrdump.log"
export TESTLOG="testbench.log"

TIMEOUT=30

. aurora

ESC=`printf "\033"`
CR=`printf "\015"`
CLEAR="$CR$ESC[K"
RED=$ESC"[0;31m"
GREEN=$ESC"[0;32m"
#YELLOW= $ESC"[0;33m"
NORMAL=$ESC"[0;39m"

FORMAT="%-40s [ %s%-7s"$NORMAL" ]"
TFORMAT="%-40s [ %s%-7s"$NORMAL" ] %6s"

print_fail()
{
    echo -n $CLEAR
    printf "$FORMAT\n" $1 $RED "fail"
}

print_success()
{
    echo -n $CLEAR
    printf "$TFORMAT\n" $1 $GREEN "success" $2
}

print_running()
{
    printf "$FORMAT" $1 "" "running"
}

cleanup_testbench()
{
	# For good measure, if something went really wrong.
	aurteardown
	destroymd $MDDISK
	exit 0
}

run_test()
{
    NAME=`basename $1`
    print_running $NAME
    tstart=`date +%s`
    $1 >> $TESTLOG
    tstop=`date +%s`
    if [ $? -eq 0 ]; then
	print_success $NAME `expr $tstop - $tstart`
    else
	print_fail $NAME
	ktrdump >> $KTRLOG
	exit 0
    fi
}

run_tests()
{
    rm -f $TESTLOG
    rm -f $KTRLOG
    touch $TESTLOG

    echo Build: `uname -sri`
    echo Host: `hostname`
    echo Test started: `date`
    printf "%-40s   %-9s   %-10s\n" "Test" "Status" "Time"
    echo "-----------------------------------------------------------"
    for t in `find $SRCROOT/tests -maxdepth 1 -name \*.sh | sort -n`; do
	run_test $t
    done
}

# Cleanup any leftover Aurora state.
aurteardown

MDDISK=`createmd`
export MDDISK=$MDDISK

if [ $# -eq 1 ]; then
	touch $TESTLOG
	run_test "$SRCROOT/tests/$1"
else
	run_tests
fi

cleanup_testbench > /dev/null 2> /dev/null
